plasma_groningen <- read.csv("HQ iMOE plasma_groningen.csv")
plasma_toddlers <- read.csv("HQ iMOE plasma_toddlers.csv")
plasma_epic.control <- read.csv("HQ iMOE plasma_epic.control.csv")
urine_dr <- read.csv("HQ iMOE urine_dr.csv")
urine_asam <- read.csv("HQ iMOE urine_asam.csv")

plasma_groningen.df <- plasma_groningen[,c(4,6:9)]
plasma_groningen.med <- t(apply(plasma_groningen.df, 2, median))
plasma_groningen.25th <- t(apply(plasma_groningen.df, 2, quantile, probs=0.25))
plasma_groningen.75th <- t(apply(plasma_groningen.df, 2, quantile, probs=0.75))
plasma_groningen.min <- t(apply(plasma_groningen.df, 2, min))
plasma_groningen.max <- t(apply(plasma_groningen.df, 2, max))
plasma_groningen.stat <- as.data.frame(rbind(plasma_groningen.med, plasma_groningen.25th, plasma_groningen.75th, plasma_groningen.min, plasma_groningen.max))
rownames(plasma_groningen.stat) <- c("Median", "25th", "75th", "Min", "Max")
write.csv(plasma_groningen.stat, file="plasma_groningen.stat.csv")

plasma_toddlers.df <- plasma_toddlers[,c(4,6:9)]
plasma_toddlers.med <- t(apply(plasma_toddlers.df, 2, median))
plasma_toddlers.25th <- t(apply(plasma_toddlers.df, 2, quantile, probs=0.25))
plasma_toddlers.75th <- t(apply(plasma_toddlers.df, 2, quantile, probs=0.75))
plasma_toddlers.min <- t(apply(plasma_toddlers.df, 2, min))
plasma_toddlers.max <- t(apply(plasma_toddlers.df, 2, max))
plasma_toddlers.stat <- as.data.frame(rbind(plasma_toddlers.med, plasma_toddlers.25th, plasma_toddlers.75th, plasma_toddlers.min, plasma_toddlers.max))
rownames(plasma_toddlers.stat) <- c("Median", "25th", "75th", "Min", "Max")
write.csv(plasma_toddlers.stat, file="plasma_toddlers.stat.csv")

plasma_epic.control.df <- plasma_epic.control[,c(5,7:10)]
plasma_epic.control.med <- t(apply(plasma_epic.control.df, 2, median))
plasma_epic.control.25th <- t(apply(plasma_epic.control.df, 2, quantile, probs=0.25))
plasma_epic.control.75th <- t(apply(plasma_epic.control.df, 2, quantile, probs=0.75))
plasma_epic.control.min <- t(apply(plasma_epic.control.df, 2, min))
plasma_epic.control.max <- t(apply(plasma_epic.control.df, 2, max))
plasma_epic.control.stat <- as.data.frame(rbind(plasma_epic.control.med, plasma_epic.control.25th, plasma_epic.control.75th, plasma_epic.control.min, plasma_epic.control.max))
rownames(plasma_epic.control.stat) <- c("Median", "25th", "75th", "Min", "Max")
write.csv(plasma_epic.control.stat, file="plasma_epic.control.stat.csv")

urine_dr.df <- urine_dr[,c(6,8:11)]
urine_dr.med <- t(apply(urine_dr.df, 2, median))
urine_dr.25th <- t(apply(urine_dr.df, 2, quantile, probs=0.25))
urine_dr.75th <- t(apply(urine_dr.df, 2, quantile, probs=0.75))
urine_dr.min <- t(apply(urine_dr.df, 2, min))
urine_dr.max <- t(apply(urine_dr.df, 2, max))
urine_dr.stat <- as.data.frame(rbind(urine_dr.med, urine_dr.25th, urine_dr.75th, urine_dr.min, urine_dr.max))
rownames(urine_dr.stat) <- c("Median", "25th", "75th", "Min", "Max")
write.csv(urine_dr.stat, file="urine_dr.stat.csv")

urine_asam.df <- urine_asam[,c(5:9)]
urine_asam.med <- t(apply(urine_asam.df, 2, median))
urine_asam.25th <- t(apply(urine_asam.df, 2, quantile, probs=0.25))
urine_asam.75th <- t(apply(urine_asam.df, 2, quantile, probs=0.75))
urine_asam.min <- t(apply(urine_asam.df, 2, min))
urine_asam.max <- t(apply(urine_asam.df, 2, max))
urine_asam.stat <- as.data.frame(rbind(urine_asam.med, urine_asam.25th, urine_asam.75th, urine_asam.min, urine_asam.max))
rownames(urine_asam.stat) <- c("Median", "25th", "75th", "Min", "Max")
write.csv(urine_asam.stat, file="urine_asam.stat.csv")
